# Generated by Django 2.2.7 on 2019-11-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191115_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='user_default.jpg', upload_to='user_images'),
        ),
    ]
