# Generated by Django 2.2.7 on 2019-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='btn_style',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
