# Generated by Django 2.2.7 on 2019-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191116_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_liked',
        ),
    ]
