# Generated by Django 2.2.7 on 2019-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20191125_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, default='pop', max_length=200, null=True),
        ),
    ]
